# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: Architekt Loew
description: website of architecture office
url: architektloew.github.io
headline: Sie bauen in der Regel nur einmal im Leben ein Haus! <br/>Da kann jeder Fehler zu viel sein.

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: .tmp/src
destination: .tmp/dist
exclude: ['assets']

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
# NOTE: Don't use @ in front of your Twitter username
author:
  name: Thomas Maximini
  email: tmaximini@gmail.com
  uri: http://thomasmaximini.com
  bio: freelance web developer
  twitter:
  github:

collections:
  architektur:
    output: true
    permalink: /architektur/:path/
  sachverstaendiger:
    output: true
    permalink: /sachverstaendiger/:path/

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
permalink: none
excerpt_separator: '<!--more-->'

# Markdown library and options
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: true

# Extending Jekyll
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
